clone_depth: 10

version: "{build}"

# What combinations to test
environment:
  matrix:
    - nodejs_version: "6"
      platform: x86
    - nodejs_version: "8"
      platform: x86
    - nodejs_version: "10"
      platform: x86

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

test_script:
  # Output useful info for debugging
  - node --version && npm --version
  - npm test

build: off

matrix:
  fast_finish: true

cache:
  - node_modules -> package.json
